### ISSUE TITLE
kubeconfig for gateway APIServer

### ISSUE THREAD

**Issue by vsxen** [kubewharf/kubegateway#10]
https://github.com/kubewharf/kubegateway/blob/main/docs/zh/quick_start.md

然后通过 kubectl 把它应用到 KubeGateway 的控制面去
`kubectl --kubeconfig <path-to-kube-config> apply -f cluster-a.kubegateway.io.yaml`

path-to-kube-config ?

**Comment by zoumo** [comment]
Thanks for the feedback.
I will add a pre-configured kubeconfig for local testing only and add a section in doc to describe it.

**Comment by zoumo** [comment]
@vsxen PR #11 adds a new way to quick start kubegateway environment on local，please refer to the doc https://github.com/kubewharf/kubegateway/blob/main/docs/zh/manually-setup.md
Thanks
