### ISSUE TITLE
kubegateway如何选择cluster?

### ISSUE THREAD

**Issue by leo1515416043** [kubewharf/kubegateway#13]
## 背景
- 场景：kube-apiserver挂载在4层LB后边，kubeConfig中的server为LB；
- kubegateway通过kubeConfig中server.host == UpstreamCluster.name进行k8s cluster的选择。kubeconfig 中的 server 填入的是 upstream cluster 的 domain，这个 domain 的 DNS 解析到gateway，gateway 通过这个 domain 来区分不同的集群；
## 问题
针对上述LB场景(不想dns适配)，如何进行集群选择？

**Comment by xuchen-xiaoying** [comment]
@zoumo please take a look at this problem.

**Comment by zoumo** [comment]
@leo1515416043 
所以你的 dns 解析是将域名解析到 4 层 LB 对么？

然后你希望的部署形式应该是 L4 LB -> kube-gateway -> kube-apiserver 对么

在这种部署情况下，不需要修改 DNS 解析，只需要在 L4 LB 中配置，将 domain 路由到 kube-gateway 就行

**Comment by xuchen-xiaoying** [comment]
> @leo1515416043 所以你的 dns 解析是将域名解析到 4 层 LB 对么？
> 
> 然后你希望的部署形式应该是 L4 LB -> kube-gateway -> kube-apiserver 对么
> 
> 在这种部署情况下，不需要修改 DNS 解析，只需要在 L4 LB 中配置，将 domain 路由到 kube-gateway 就行

他们没有使用 域名，kubeconfig 使用的 vip 访问的 4 层 LB。

**Comment by leo1515416043** [comment]
没有使用域名和dns，使用LB的VIP。
在考虑如何适配kubegateway。

**Comment by xuchen-xiaoying** [comment]
> 没有使用域名和dns，使用LB的VIP。 在考虑如何适配kubegateway。

一个 4 层 lb 只对应一个集群是吧？ @zoumo 考虑支持 hostname 通配符?

**Comment by leo1515416043** [comment]
> 一个 4 层 lb 只对应一个集群是吧？

是的，每个k8s cluster都有一个LB

**Comment by xuchen-xiaoying** [comment]
> > 一个 4 层 lb 只对应一个集群是吧？
> 
> 是的，每个k8s cluster都有一个LB

如果一个 lb 只对应一个集群，一个 kubegateway 只配置一个 upstreamcluster 对象，通过通配符 (*) 进行 hostname 的匹配。

**Comment by zoumo** [comment]
@leo1515416043 通过 vip 访问 4 层 LB 转发给 kube-gateway 的时候需要确认以下几点
1. LB 转发给 kube-gateway 的时候，kube-gateway 收到的 tls 握手中的 serverName 是 vip 还是 kube-gateway 的 ip，4 层转发用的是 NAT 它理论上只改了 IP 封包中的目的地址 IP 应该不会改 clientHello 中的内容，所以应该还是 vip
2. kube-gateway 收到的 http 包中的 host 指向的是否为 vip

如果上述两个都是 vip 的话，那么只需要在 kube-gateway 配置一个 name=vip 的 upstreamCluster 即可，让客户端请求发送给 lb 然后 lb 转发给 kube-gateway，gateway 转发给 apiserver

**Comment by xuchen-xiaoying** [comment]
> @leo1515416043 通过 vip 访问 4 层 LB 转发给 kube-gateway 的时候需要确认以下几点
> 
> 1. LB 转发给 kube-gateway 的时候，kube-gateway 收到的 tls 握手中的 serverName 是 vip 还是 kube-gateway 的 ip，4 层转发用的是 NAT 它理论上只改了 IP 封包中的目的地址 IP 应该不会改 clientHello 中的内容，所以应该还是 vip
> 2. kube-gateway 收到的 http 包中的 host 指向的是否为 vip
> 
> 如果上述两个都是 vip 的话，那么只需要在 kube-gateway 配置一个 name=vip 的 upstreamCluster 即可，让客户端请求发送给 lb 然后 lb 转发给 kube-gateway，gateway 转发给 apiserver

@leo1515416043 如 @zoumo 所言，gateway 收到的 http 请求中，host 应该仍然为 lb 的 vip，所以你把 upstreamCluster 的 name 设置成这个 vip 即可？

**Comment by xuchen-xiaoying** [comment]
@leo1515416043 看下，还有问题不？
