### ISSUE TITLE
kube-gateway proxy到既有集群

### ISSUE THREAD

**Issue by leo1515416043** [kubewharf/kubegateway#14]
#### 期望效果
本地启动的kube-gateway，proxy到既有集群(非本地)

#### 过程
仿照local-up.sh的相关步骤，生成的upStreamCluster.name 和 kubeConfig中的severHost均为"localhost"

#### 报错
E1123 20:00:55.545031    2984 upstream_controller.go:217] upstream health check failed, cluster="localhost" endpoint="https://x.x.x.x:6443" reason="Failure" message="Get \"https://x.x.x.x:6443/healthz?timeout=5s\": x509: certificate is valid for xx, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not localhost"

**Comment by zoumo** [comment]
感谢反馈。

TLDR: 要解决这个问题有两个办法
1. 在你的现有集群中，给 apiserver 启动的证书签入 localhost 的域名
2. 或者是修改 kubegateway 的 upstreamCluster.Name 将它改为 apiserver 证书中已有的域名 xx.domain，然后 kubeconfig 中的配置也做相应的修改，最后在本地的 hosts 中将 xx.domain 解析到 kubegateway 所在的节点，本例中应该是 127.0.0.1


问题原因：
这里可能是理解上有偏差，KubeGateway 希望实现的是对客户端透明的代理，增加或减少 KubeGateway 的代理对客户端无感知，也即客户端不需要修改它本身的配置。
回到这个问题中，你在配置的时候 UpstreamCluster.Name 应为已有集群的域名，而不是应该是 'localhost' 这种本地测试域名。增加 KubeGateway 的代理后唯一需要改变的是该域名的 DNS 解析

**Comment by xuchen-xiaoying** [comment]
kubegateway 在做 health check 的时候，会校验 upstream apiserver 的证书的 serverName 是否等于 upStreamCluster 对象的 name，防止连接到错误的 apiserver 实例。从报错来看，upstream apiserver 的证书中包含了以下域名 

xx, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local

但是没有 upstreamCluster 的 name `localhost` ，导致健康监测出问题。 @leo1515416043 你可以把 upstreamCluster 的名字改为 kubernetes 或者 kubernetes.default 试一下。

**Comment by xuchen-xiaoying** [comment]
@zoumo 我觉得为了更好的支持平滑迁移，是否可以支持 upstream 健康监测的 serverName 覆盖？路由匹配的时候使用 upstreamCluster.Name，健康监测的时候证书校验的时候，可选使用另外的 name。

**Comment by leo1515416043** [comment]
感谢回复，已解决。
