### ISSUE TITLE
相比原生APF，kubegateaway限流的使用场景和优缺点

### ISSUE THREAD

**Issue by leo1515416043** [kubewharf/kubegateway#15]
## 背景
kubernetes原生已经支持限流，简称[APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/)。

## 问题
- 相比原生APF，kubegateaway限流的使用场景和优缺点有哪些？

**Comment by zoumo** [comment]
1. APF 的设计理念是好的，它的配置有一些不直观，而且会较为复杂。
APF 特性包含几个不同的功能。 传入的请求通过 FlowSchema 按照其属性分类，并分配优先级。 每个优先级维护自定义的并发限制，加强了隔离度，这样不同优先级的请求，就不会相互饿死。 在同一个优先级内，公平排队算法可以防止来自不同 流（Flow） 的请求相互饿死。 该算法将请求排队，通过排队机制，防止在平均负载较低时，通信量突增而导致请求失败。

2. kubegateway 的限流更多考虑的是对 apiserver 的保护
kubegateway 的限流参考了 APF 的设计，但是最终做了一些简化，让它看起来跟直接。在 kubegateway 这一层，更看重的是对 apiserver 的保护，所以限流不仅仅是为了公平或者排队，更多时候是为了熔断，在异常情况下减少 apiserver 收到的请求数量，由于过载而出现 OOM 等问题。比如当集群出现雪崩的时候，我们需要能在 apiserver 之前将请求熔断之后再慢慢放流量进来恢复集群

3. kubegateway 和 APF 并不冲突
kubegateway 的限流适合作为第一道防线来防止 apiserver 过载，而 APF 可以对单个 apiserver 的不同请求进行分类分优先级限制和排队，它们并不冲突

**Comment by xuchen-xiaoying** [comment]
@leo1515416043 如 @zoumo 所说，APF 配置复杂，不直观。

1. 针对每一个 PriorityLevelConfiguration ，只能限制相对比例 assuredConcurrencyShares，这个比例需要除以所有 PriorityLevelConfiguration 总的 Share 之和，才能计算出绝对比例，不能直观的限制 QPS 和 max-in-inflight 数。
2. queue 的配置相对复杂，内部排队、计算逻辑不透明，理解成本较高。

**Comment by xuchen-xiaoying** [comment]
@leo1515416043 看下，问题解决了吗？

**Comment by leo1515416043** [comment]
3ks
