### ISSUE TITLE
支持设置默认的UpstreamCluster，不根据UpstreamCluster名称匹配转发

### ISSUE THREAD

**Issue by zjzhangkui** [kubewharf/kubegateway#17]
目前要求UpstreamCluster的名称和kubeconfig的cluster的server地址的域名相同表示转发到对应的k8s集群的apiserver地址，对于一个kubegateway只代理一个upstreamcluster时，如果能支持代理转发到默认的upstreamcluster，只需要将上游k8s集群的kubeconfig的server地址设置为kubegateway的地址，就可以走kubegateway代理，即原kubeconfig只需要变更server地址就可以切换是直连apiserver还是通过kubegateway代理，这样就不需要专门为kubegateway代理专门申请一个新的域名和证书，是不是很方便呢？

**Comment by zoumo** [comment]
我没有特别理解你的问题，我尝试解释一下你看有没有回答你的问题。

在没有 kube-gateway 做为代理之前，我们通常会采用 nginx haproxy 或者其他的 lb 来代理 apiserver 的流量，这时候域名的解析是解析到这些 lb 所在的节点，而不是 apiserver。引入 kube-gateway 后，只需要替换掉原来 lb 的位置，将域名解析到 kube-gateway 就可以了，并不需要为 kube-gateway 单独申请域名解析和证书

至于默认 upstreamcluster 的问题，kubegateway 在设计的时候考虑的是代理多个而不是一个集群，所以在语义上不应该存在默认集群的概念

**Comment by zjzhangkui** [comment]
原先是阿里云的slb ip转发到apiserver的3个节点， kubeconfig的server地址是slb ip， 目标是想用这个kubeconfig 改下server地址改成kubegateway的地址，使用kubegateway代理，然后kubegateway转发到默认的一个upstreamcluster， 这样不需要新增域名或新增slb ip, 同时保留了原先slb直接转发apiserver， 不过这个也只在一个kubegateway代理一个upstreamcluster的场景有用， 与设计初衷不符合

**Comment by xuchen-xiaoying** [comment]
> 原先是阿里云的slb ip转发到apiserver的3个节点， kubeconfig的server地址是slb ip， 目标是想用这个kubeconfig 改下server地址改成kubegateway的地址，使用kubegateway代理，然后kubegateway转发到默认的一个upstreamcluster， 这样不需要新增域名或新增slb ip, 同时保留了原先slb直接转发apiserver， 不过这个也只在一个kubegateway代理一个upstreamcluster的场景有用， 与设计初衷不符合

@zjzhangkui 请问下，你这个需求强烈吗？

**Comment by zjzhangkui** [comment]
> > 原先是阿里云的slb ip转发到apiserver的3个节点， kubeconfig的server地址是slb ip， 目标是想用这个kubeconfig 改下server地址改成kubegateway的地址，使用kubegateway代理，然后kubegateway转发到默认的一个upstreamcluster， 这样不需要新增域名或新增slb ip, 同时保留了原先slb直接转发apiserver， 不过这个也只在一个kubegateway代理一个upstreamcluster的场景有用， 与设计初衷不符合
> 
> @zjzhangkui 请问下，你这个需求强烈吗？

@xuchen-xiaoying 现在计划有些k8s集群专用一个kubegateway， 有些是共用，还是按设计的初衷为每个k8s集群申请一个域名，apiserver证书certSANs加域名重新生成一下， 现在不需要这个需求了
另外请教一下实践落地部署的情况，是将kubegateway以及etcd部署在master节点，还是单独规划了节点专门部署kubegateway组件？
感谢！

**Comment by xuchen-xiaoying** [comment]
> > > 原先是阿里云的slb ip转发到apiserver的3个节点， kubeconfig的server地址是slb ip， 目标是想用这个kubeconfig 改下server地址改成kubegateway的地址，使用kubegateway代理，然后kubegateway转发到默认的一个upstreamcluster， 这样不需要新增域名或新增slb ip, 同时保留了原先slb直接转发apiserver， 不过这个也只在一个kubegateway代理一个upstreamcluster的场景有用， 与设计初衷不符合
> > 
> > 
> > @zjzhangkui 请问下，你这个需求强烈吗？
> 
> @xuchen-xiaoying 现在计划有些k8s集群专用一个kubegateway， 有些是共用，还是按设计的初衷为每个k8s集群申请一个域名，apiserver证书certSANs加域名重新生成一下， 现在不需要这个需求了 另外请教一下实践落地部署的情况，是将kubegateway以及etcd部署在master节点，还是单独规划了节点专门部署kubegateway组件？ 感谢！

在我们的场景中，由于 kubegateway 的流量比较大，是单独的机器和 etcd 集群。
