### ISSUE TITLE
通过kubernetes service连接apiserver的组件如何批量切换kubegateway代理

### ISSUE THREAD

**Issue by zjzhangkui** [kubewharf/kubegateway#18]
很多组件（开源组件，自定义控制器以及informer类组件）默认是通过kubernetes.default的service访问apiserver的，如果要保留默认的kubernetes service连接apiserver地址不变，有些组件要切换为kubegateway代理，是不是需要针对每个组件配置apisever地址，如果有些组件没有提供apiserver配置参数，还需要做一些改造，针对这类场景有没最佳实践建议？

**Comment by zoumo** [comment]
这种 InCluster 的客户端在初始化的时候使用的是 ENV 中的 KUBERNETES_SERVICE_HOST 和 KUBERNETES_SERVICE_PORT 这两个环境变量来决定连接的 apiserver 地址，这个环境变量由 kubelet 从 default namespace 下的 kubernetes service 中得到，但是如果 pod 在启动之前自己配置了这两个环境变量，则 kubelet 是不会进行覆盖的。

1. 所以你可以手动地在 pod 创建之前提前将 KUBERNETES_SERVICE_HOST 配置为域名
2. 或者你可以通过一个 mutatingwebhook 来为所有 pod 修改这个值（在1.20之前版本的 k8s 中你可以通 podpreset 来做到）

**Comment by xuchen-xiaoying** [comment]
> 这种 InCluster 的客户端在初始化的时候使用的是 ENV 中的 KUBERNETES_SERVICE_HOST 和 KUBERNETES_SERVICE_PORT 这两个环境变量来决定连接的 apiserver 地址，这个环境变量由 kubelet 从 default namespace 下的 kubernetes service 中得到，但是如果 pod 在启动之前自己配置了这两个环境变量，则 kubelet 是不会进行覆盖的。
> 
> 1. 所以你可以手动地在 pod 创建之前提前将 KUBERNETES_SERVICE_HOST 配置为域名
> 2. 或者你可以通过一个 mutatingwebhook 来为所有 pod 修改这个值（在1.20之前版本的 k8s 中你可以通 podpreset 来做到）

建议方案 1.

**Comment by zjzhangkui** [comment]
> 这种 InCluster 的客户端在初始化的时候使用的是 ENV 中的 KUBERNETES_SERVICE_HOST 和 KUBERNETES_SERVICE_PORT 这两个环境变量来决定连接的 apiserver 地址，这个环境变量由 kubelet 从 default namespace 下的 kubernetes service 中得到，但是如果 pod 在启动之前自己配置了这两个环境变量，则 kubelet 是不会进行覆盖的。
> 
> 1. 所以你可以手动地在 pod 创建之前提前将 KUBERNETES_SERVICE_HOST 配置为域名
> 2. 或者你可以通过一个 mutatingwebhook 来为所有 pod 修改这个值（在1.20之前版本的 k8s 中你可以通 podpreset 来做到）

好的，谢谢！
