### ISSUE TITLE
使用featuregate annotation熔断集群，无法回滚

### ISSUE THREAD

**Issue by leo1515416043** [kubewharf/kubegateway#22]
## 背景
集群降级熔断功能：使用featuregate，给upstreamCluster增加annotation：【proxy.kubegateway.io/feature-gates: DenyAllRequests=true】

## 现象
将上述annotation remove后，upstreamCluster仍旧处于熔断中

**Comment by zoumo** [comment]
感谢反馈，我将于本周内修复
