### ISSUE TITLE
How does kube-gateway downgrade

### ISSUE THREAD

**Issue by zhifei92** [kubewharf/kubegateway#25]
**What would you like to be added**:
I don't see a degraded configuration，that is implemented by dispatchPolicies. rules?
**Why is this needed**:

**Comment by zoumo** [comment]
@zhifei92 
yes，downgrade means something that when the upstream cluster has pressure, you can 
1. set flow control on specific reqeusts to allow less reqeusts access apiserver
2. or rejects some expansive requests, like list pods
3. or rejects all reqeusts

the first two can be implemented by flowcontrol and spec.dispatchPolicies
the last can be implemented by adding annotation "proxy.kubegateway.io/feature-gates: DenyAllRequests=true"

**Comment by zhifei92** [comment]
“DenyAllRequests=true”  have the same effect as removing lb‘s rs.  I think it is more convenient to configure the downgrade policy in advance and open it by "switch" when needed

**Comment by zoumo** [comment]
what kind downgrade policy do you mean?

**Comment by zhifei92** [comment]
> what kind downgrade policy do you mean?

sorry, i got it wrong. now , i understand

**Comment by zhifei92** [comment]
but, qps can‘t be set to 0, so how to "rejects some expansive requests, like list pods"

**Comment by zoumo** [comment]
> qps can‘t be set to 0

@zhifei92 maxrequestinflight flowcontrol can be set to 0, 0 means reject all requests

https://github.com/kubewharf/kubegateway/blob/main/docs/en/quick_start.md#maxrequestsinflight

**Comment by zhifei92** [comment]
sorry，i forgot to close this issue.
