### ISSUE TITLE
pull方式拉取「代理面」的prometheus metrics

### ISSUE THREAD

**Issue by leo1515416043** [kubewharf/kubegateway#26]
## 希望
代理面暴露prometheus metrics && 可以通过pull方式拉取metrics

**Comment by zoumo** [comment]
感谢反馈，我计划在下个双月中单独添加一个 proxy-metrics 的端口来对外提供代理层的 metrics

**Comment by zjzhangkui** [comment]
> 感谢反馈，我计划在下个双月中单独添加一个 proxy-metrics 的端口来对外提供代理层的 metrics

@zoumo 目前proxy-metrics 可以通过什么方式获取？
