### ISSUE TITLE
如何实现apiserver的watch代理？

### ISSUE THREAD

**Issue by noovertime7** [kubewharf/kubegateway#47]
我在使用`proxy := httputil.NewSingleHostReverseProxy(apiServerURL)`对apiserver进行代理时，当收到watch=true的请求时，报错`httputil: ReverseProxy read error during body copy: context deadline exceeded`,我看`kubegateway`项目是支持的，万分感谢您的回复

**Comment by xuqingyun** [comment]
你能分享一下相关代码吗，kubegateway中对于watch代理并没有特殊的处理，都是通过ReverseProxy实现的。是不是什么地方设置了context超时？

**Comment by noovertime7** [comment]
抱歉，是我使用的框架导致的，我用原生的已经修复了，感谢回复 @xuqingyun
