### ISSUE TITLE
how to create kubegateway crds

### ISSUE THREAD

**Issue by ywzrb** [kubewharf/kubegateway#54]
![image](https://github.com/kubewharf/kubegateway/assets/51774120/ee2d4086-a65a-49c5-bd22-c022b8a72a2a)

**Comment by xuqingyun** [comment]
kubegateway crds are all built-in types and do not need to be created by users.
upstreamclusters are created in kube-gateway controlplane, do you specific the right server addr for kubectl? 
could you please show the api-resources of ateway-control-plane and gateway-proxy?  for example
```
kubectl --context gateway-control-plane api-resources
kubectl --context gateway-proxy api-resources
```

**Comment by ywzrb** [comment]
如何访问这个集群
![image](https://github.com/kubewharf/kubegateway/assets/51774120/b14d12d6-8425-4f48-8722-dd51c17c572f)

**Comment by xuqingyun** [comment]
use `kubectl -s https://127.0.0.1:9443  --insecure-skip-tls-verify api-resources`

```
% kubectl -s https://127.0.0.1:9443  --insecure-skip-tls-verify api-resources
NAME                  SHORTNAMES   APIVERSION                      NAMESPACED   KIND
namespaces            ns           v1                              false        Namespace
secrets                            v1                              true         Secret
serviceaccounts       sa           v1                              true         ServiceAccount
leases                             coordination.k8s.io/v1          true         Lease
ratelimitconditions                proxy.kubegateway.io/v1alpha1   false        RateLimitCondition
upstreamclusters                   proxy.kubegateway.io/v1alpha1   false        UpstreamCluster
clusterrolebindings                rbac.authorization.k8s.io/v1    false        ClusterRoleBinding
clusterroles                       rbac.authorization.k8s.io/v1    false        ClusterRole
rolebindings                       rbac.authorization.k8s.io/v1    true         RoleBinding
roles                              rbac.authorization.k8s.io/v1    true         Role

% kubectl -s https://127.0.0.1:9443  --insecure-skip-tls-verify get upstreamclusters
NAME                      CREATED AT
devbox                    2023-12-15T03:01:14Z
test1-control-plane       2023-12-14T09:05:34Z
```

**Comment by ywzrb** [comment]
配置完upstreamclusters，把kubeconfig的server地址换成kube-gateway代理6443端口就可以测试了吗

**Comment by xuqingyun** [comment]
> 配置完upstreamclusters，把kubeconfig的server地址换成kube-gateway代理6443端口就可以测试了吗

是的，但不是直接把server地址换成kube-gateway的ip:port，而是将域名解析到kube-gateway的ip，可以通过/etc/hosts将域名解析到127.0.0.1

**Comment by ywzrb** [comment]
这个代表upstreamclusters配置成功了吗
![image](https://github.com/kubewharf/kubegateway/assets/51774120/31aa4780-def6-4e37-873d-5b61159b6e02)

**Comment by xuqingyun** [comment]
是的
